# 넘파이 패키지 이용하기
* 배열 또는 백터 계산을 위한 패키지
* ndarray 자료형을 이용

* 배열 생성: arr:np.random.randin(5,8)
* 배열 연산 : 일반 연산자 이용 >> 파이썬 리스트 보다 연산속도가 압도적으로 빠름, 빅데이터 다룰때 사용함
* 단 , 행렬곱은 *(성분곱) 대신 arr.dot(arr2)이용


## 넘파이 인덱싱, 슬라이싱

* arr변수에 array([1,2,3,6,5,4])가 있다고 가정할 때, <br>
arr[-2] == array([5]) <br>
arr[3:] == array([6,5,4]) <br>
* 리스트 형태의 인덱싱과 슬라이싱이 가능
* array([1,2,3],[4,5,6],[7,8,9]) 이중 리스트 가능

## 넘파이 파일 처리
* np.save('filename,npy, arr) <br>
arr = np.load('filename.npy) 
* 저장된 파일은 바이너리 형식이므로,(0,1로 표현) <br>
판다스의 csv 등의 테이블 파일 저장에 비해 경제적 (용량, 속도 빠름)

In [3]:
import numpy as np
arr = np.array([1,2,3])

In [10]:
arr

array([1, 2, 3])

In [11]:
arr[-1]

3

In [12]:
arr[1:]

array([2, 3])

In [15]:
arr2 = np.array([4,5,6])

In [16]:
arr + arr2  # 배열의 연산 (행렬연산)

array([5, 7, 9])

In [17]:
[1,2,3] + [4,5,6] # 리스트의 연산

[1, 2, 3, 4, 5, 6]

In [18]:
arr - arr2

array([-3, -3, -3])

In [19]:
arr * arr2

array([ 4, 10, 18])

In [21]:
arr.dot(arr2) ## 행렬곱

32

In [23]:
arr/arr2

array([0.25, 0.4 , 0.5 ])

In [24]:
arr % arr2

array([1, 2, 3])

In [25]:
arr // arr2

array([0, 0, 0])

In [28]:
arr + 12 ## 브로드캐스팅 지원 함(각각 요소에 모두 연산 하는것)

array([13, 14, 15])

In [33]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr3.shape #(몇차원인지 파악하는 방법)

(3, 3)

In [31]:
[[1,2,3],[4,5,6],[7,8,9]]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [38]:
arr3 * 4

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [41]:
arr3 + arr3

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [42]:
arr3 - arr

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])

In [44]:
arr3 / arr

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ],
       [7. , 4. , 3. ]])

In [46]:
arr3.dot(arr2)

array([ 32,  77, 122])

In [69]:
arr4 = np.random.randint(5,8) # 5~8 사이 무작위 정수 랜덤으로 저장
arr4

7

In [72]:
num = arr4 = np.random.randint(1,7)
print(f'주사위 값은 {num}입니다')

주사위 값은 6입니다


---
### 절대경로와 상대경로
1. 절대경로 : F/신입강의/data/221116.ipynb와 같은 형태의 경로
- 파이썬이나 다른 OS에선 /를 /로 대체해서 사용
2. 상대경로: ./arr3.npy와 같은 형태의 경로
* ./표기는 현재 파일과 같은 경로
* ../표기는 현재 파일에서 상위 디렉토리라는 뜻
* ./folder/표기는 현재 경로에서 folder라는 폴더로 들어간다는 뜻

In [80]:
np.save('../실습 데이터/arr3.npy',arr3)

In [76]:
new_arr  = np.load('./arr3.npy')
new_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 외부 데이터를 이용한 데이터 처리
* 공공데이터포털을 이용
* 주어진 데이터에서 분류, 평균 비교, 연산 등의 작업 진행 <br>

* 각 분류 및 연산에서 실질적인 의미를 가지고 있는지 확인
* 결측치, 오기재된 데이터 처리방법 검토해보기

## 실습 1
* 아래 데이터를 2022년 분기별 데이터로 분류를 한다
* 분류된 데이터는 각각 df_3, df_6, df_9,df_12라는 변수로 저장한다
* df_6과 df_12의 지분율 평균을 비교한다
* 지분율이 가장 높은 기관이 있는 달과 가장 낮은 기관이 있는 달을 확인한다

In [4]:
import pandas as pd
df = pd.read_csv('C:/Users/user/Desktop/230102~/실습 데이터/국민연금공단_대량보유주식 보고내역_20221005.csv',
                 encoding= 'cp949',index_col=0) # 0번째 컬럼을 인덱스로 사용
df.head(2)

발행기관명   보고서 작성기준일  지분율(퍼센트)
번호                                 
1     ㈜파크시스템스  2022-07-22      5.04
2   롯데칠성음료(주)  2022-07-26      9.95

In [176]:
a = [] 
for i in range(1,max(df.index)+1):
    if int(df.loc[i,'보고서 작성기준일'].split('-')[1]) >9:
        a.append(4)
    elif int(df.loc[i,'보고서 작성기준일'].split('-')[1]) >6:
        a.append(3)
    elif int(df.loc[i,'보고서 작성기준일'].split('-')[1]) >3:
        a.append(2)
    else:
        a.append(1)
df['분기_1']  =a
df

발행기관명   보고서 작성기준일  지분율(퍼센트)  분기  3분기 평균  분기_1
번호                                                     
1       ㈜파크시스템스  2022-07-22      5.04   3     NaN     3
2     롯데칠성음료(주)  2022-07-26      9.95   3     NaN     3
3      한화솔루션(주)  2022-07-01      8.93   3     NaN     3
4    현대엘리베이터(주)  2022-07-26      5.83   3     NaN     3
5     롯데관광개발(주)  2022-07-25      6.17   3     NaN     3
..          ...         ...       ...  ..     ...   ...
124       효성티앤씨  2022-07-26      7.65   3     NaN     3
125     (주)세아제강  2022-09-26      5.13   3     NaN     3
126      현대오토에버  2022-08-16      7.04   3     NaN     3
127    피에스케이(주)  2022-09-29      7.97   3     NaN     3
128     솔루스첨단소재  2022-07-15      5.15   3     NaN     3

[128 rows x 6 columns]

In [181]:
# 답안
def split_date(x):
    month = int(x.split('-')[1])
    
    if month>9:
        return 4
    elif month>6:
        return 3
    elif month>3:
        return 2
    else:
        return 1

In [109]:
df['분기'] = df['보고서 작성기준일'].apply(lambda x : split_date(x))
df

발행기관명   보고서 작성기준일  지분율(퍼센트)  분기
번호                                       
1       ㈜파크시스템스  2022-07-22      5.04   3
2     롯데칠성음료(주)  2022-07-26      9.95   3
3      한화솔루션(주)  2022-07-01      8.93   3
4    현대엘리베이터(주)  2022-07-26      5.83   3
5     롯데관광개발(주)  2022-07-25      6.17   3
..          ...         ...       ...  ..
124       효성티앤씨  2022-07-26      7.65   3
125     (주)세아제강  2022-09-26      5.13   3
126      현대오토에버  2022-08-16      7.04   3
127    피에스케이(주)  2022-09-29      7.97   3
128     솔루스첨단소재  2022-07-15      5.15   3

[128 rows x 4 columns]

In [110]:
df_9 = df[df['분기'] ==3]
df_12 = df[df['분기'] == 4]

In [126]:
mean_9 = df_9['지분율(퍼센트)'].mean()
mean_12 = df_12['지분율(퍼센트)'].mean()
mean_9, mean_12


(7.380079365079366, 9.66)

In [129]:
print('''3,4분기 지분율의 평균은 각각 %.3f퍼센트, %.3f퍼센트로,
      4분기 지분율의 평균이 %.3f퍼센트보다 더 높습니다.''' 
      %(mean_9, mean_12, mean_12 - mean_9)) # 복잡한 연산시 에러발생 가능성 있기 때문에 변수로 따로 빼는 것을 권장함

3,4분기 지분율의 평균은 각각 7.380퍼센트, 9.660퍼센트로,
      4분기 지분율의 평균이 2.280퍼센트보다 더 높습니다.


In [140]:
max_val = df['지분율(퍼센트)'].max()
min_val = df['지분율(퍼센트)'].min()

In [138]:
df.index[df['지분율(퍼센트)'] == max_val][0]
df.loc[83,'발행기관명']

'(주)SBS'

In [141]:
df.index[df['지분율(퍼센트)'] == min_val][0]

69

In [142]:
df.loc[69,'발행기관명']

'(주)코리아써키트'

## 실습 2
* 아래 데이터프레임에서 무역수지가 적자인 그룹과 흑자인 그룹을 나눕니다.
* 수출건수가 상위 10%인 그룹을 구합니다
* 수입건수의 평균을 구하고, 그 값에 가장 가까운 그룹을 구합니다.

In [19]:
import openpyxl
df2= pd.read_excel('C:/Users/user/Desktop/230102~/실습 데이터/FTA무역통계_20230109000015.xls', header = 4)
df2.head(5)

c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")


기간    FTA명                  수출건수                  수출금액  \
0  2022    RCEP             6,474,383           287,564,087   
1  2022  한-EFTA                26,912             1,794,418   
2  2022    한-EU               882,224            67,684,624   
3  2022  한-뉴질랜드                36,305             3,139,637   
4  2022    한-미국             2,186,357           100,446,018   

                   수입건수                  수입금액                  무역수지  
0            11,944,545           292,113,146            -4,549,059  
1                75,489             4,810,598            -3,016,180  
2             4,734,145            66,716,800               967,825  
3               455,563             1,743,951             1,395,687  
4            18,531,680            74,972,585            25,473,433

### 실습 2-1

In [22]:
int(df2['무역수지'][0].replace(' ','').replace(',',''))

-4549059

In [23]:
'-'in df2['무역수지'][0] ## -가 있는지 없는지 확인

True

In [24]:
def number(x):
    y = int(x.replace(' ','').replace(',','')) 
    return y>0


In [25]:
m= df2['무역수지'].apply(lambda x : number(x)) ## 무역수지가 흑자인 그룹
df3 = df2[m]
df3

기간    FTA명                  수출건수                  수출금액  \
2   2022    한-EU               882,224            67,684,624   
3   2022  한-뉴질랜드                36,305             3,139,637   
4   2022    한-미국             2,186,357           100,446,018   
5   2022   한-베트남               582,908            56,212,924   
6   2022  한-싱가포르               749,118            18,696,289   
7   2022   한-아세안             2,775,570           115,599,623   
8   2022    한-영국               108,368             5,862,160   
9   2022    한-인도               193,395            17,391,372   
10  2022    한-중국             1,325,620           144,611,224   
11  2022    한-중미                28,606             1,388,730   
14  2022  한-콜롬비아                14,045               862,924   
15  2022    한-터키                82,688             7,059,423   

                    수입건수                  수입금액                  무역수지  
2              4,734,145            66,716,800               967,825  
3                455,563             1,743,951             1,395,687  
4             18,531,680            74,972,585            25,473,433  
5                860,372            24,850,108            31,362,815  
6                151,934             9,315,582             9,380,706  
7              1,839,987            75,744,022            39,855,602  
8                386,507             5,374,130               488,030  
9                182,655             8,403,685             8,987,687  
10             6,775,116           142,753,918             1,857,306  
11                10,003               933,363               455,367  
14                11,286               636,784               226,140  
15                46,380             1,287,251             5,772,172

In [327]:
df4 = df2[-m] ## 무역수지가 적자인 그룹
df4

기간    FTA명                  수출건수                  수출금액  \
0   2022    RCEP             6,474,383           287,564,087   
1   2022  한-EFTA                26,912             1,794,418   
12  2022    한-칠레                30,137             1,425,386   
13  2022   한-캐나다               212,405             7,224,014   
16  2022    한-페루                13,929               721,030   
17  2022    한-호주               191,729            17,396,124   

                    수입건수                  수입금액                  무역수지  
0             11,944,545           292,113,146            -4,549,059  
1                 75,489             4,810,598            -3,016,180  
12                16,553             6,264,483            -4,839,097  
13               329,449             7,966,998              -742,985  
16                10,024             2,734,129            -2,013,099  
17               560,089            41,235,660           -23,839,536

### 실습 2-2 

In [26]:
def count_top10(x):
    y = int(x.replace(' ','').replace(',','')) 
    return y
df2['수출건수'].apply(lambda x : count_top10(x))

0     6474383
1       26912
2      882224
3       36305
4     2186357
5      582908
6      749118
7     2775570
8      108368
9      193395
10    1325620
11      28606
12      30137
13     212405
14      14045
15      82688
16      13929
17     191729
Name: 수출건수, dtype: int64

In [329]:
df2.columns

Index(['기간', 'FTA명', '수출건수', '수출금액', '수입건수', '수입금액', '무역수지'], dtype='object')

In [27]:
for i in df2.columns[2:]:
    df2[i] = df2[i].apply(lambda x : count_top10(x))
df2.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   기간      18 non-null     int64 
 1   FTA명    18 non-null     object
 2   수출건수    18 non-null     int64 
 3   수출금액    18 non-null     int64 
 4   수입건수    18 non-null     int64 
 5   수입금액    18 non-null     int64 
 6   무역수지    18 non-null     int64 
dtypes: int64(6), object(1)
memory usage: 1.1+ KB


In [335]:
df2.shape ## 상위 10% =1.8개 약 2개

(18, 7)

In [338]:
df2.sort_values('수출건수').iloc[-2:]

기간   FTA명     수출건수       수출금액      수입건수       수입금액      무역수지
7  2022  한-아세안  2775570  115599623   1839987   75744022  39855602
0  2022   RCEP  6474383  287564087  11944545  292113146  -4549059

In [351]:
format(115245654,',') ## 숫자의 세자리마다 ,찍기

'115,245,654'

### 실습 2-3

In [28]:
mean_1 = df2['수입건수'].mean()
mean_1

2606765.388888889

In [30]:
arr1 = np.array([df2['수입건수']]) # np는 [0,0,0,0,0] 이고 df는 세로이기 때문에 사이즈가 달라서 연산이 안됨
arr1                                                         
df2['편차_수입건수'] = arr1 - 2606765

ValueError: Length of values (1) does not match length of index (18)

In [31]:
import_mean = df2['수입건수'].mean()
import_mean

2606765.388888889

In [32]:
dev_min =  [9999999999,0]
for i in df2.index:
    dev = df2.loc[i,'수입건수'] - import_mean
    
    if dev_min[0] > abs(dev): ## 절댓값 구하는 함수 abs
        dev_min = [abs(dev),i]

In [33]:
dev_min

[766778.388888889, 7]

In [34]:
import_calc = df2['수입건수'] - import_mean
import_calc = import_calc.apply(lambda x: abs(x))
import_calc.sort_values()

7     7.667784e+05
5     1.746393e+06
17    2.046676e+06
2     2.127380e+06
3     2.151202e+06
8     2.220258e+06
13    2.277316e+06
9     2.424110e+06
6     2.454831e+06
1     2.531276e+06
15    2.560385e+06
12    2.590212e+06
14    2.595479e+06
16    2.596741e+06
11    2.596762e+06
10    4.168351e+06
0     9.337780e+06
4     1.592491e+07
Name: 수입건수, dtype: float64

## 실습 3
* 교육인원을 아래 조건에 따라 3그룹으로 나눕니다.
    * 30명 이하 그룹
    * 500명 이하 그룹
    * 500명 초과 그룹
* 각 그룹별로 어느 지역이 가장 많은지 살펴봅시다.

In [184]:
df3 = pd.read_csv('C:/Users/user/Desktop/230102~/실습 데이터/도로교통공단_사회교육_교육실적정보_20201231.csv',
                  encoding='cp949',index_col=0)
df3.head(2)

교육일자  지부코드  교육구분               교육구분_1   교육장소  교육인원    교육시작시간  \
실적번호                                                                         
777624  2020-01-07  인천지부     3  기관/단체, 기업체 등 교통안전교육  171연대   162  10:00:00   
777625  2020-01-07  인천지부     3  기관/단체, 기업체 등 교통안전교육  172연대    43  14:00:00   

          교육종료시간  
실적번호              
777624  12:00:00  
777625  16:00:00

In [369]:
df3['교육인원'].mean()

31.516191904047975

In [370]:
df3['교육인원'].max()

1000

In [185]:
m = df3['교육인원'] <=30 
df_30 = df3[m]
df_30 

교육일자    지부코드  교육구분               교육구분_1               교육장소  \
실적번호                                                                       
777867  2020-01-10    경북지부     2           청소년 교통안전교육           구미 보호관찰소   
777961  2020-01-15    인천지부     4            노인 교통안전교육         인천노인인력개발센터   
777971  2020-01-21    인천지부     4            노인 교통안전교육         인천노인인력개발센터   
778003  2020-01-20    대구지부     2           청소년 교통안전교육     대구행복한미래제단 301호   
778004  2020-01-30    대구지부     3  기관/단체, 기업체 등 교통안전교육        공군 제16전투비행단   
...            ...     ...   ...                  ...                ...   
784810  2020-11-12  광주전남지부     1           어린이 교통안전교육          여수 중앙어린이집   
784811  2020-11-12  광주전남지부     1           어린이 교통안전교육          여수 중앙어린이집   
788112  2020-05-24  울산경남지부     1           어린이 교통안전교육            예다움어린이집   
789143  2020-12-04    대구지부     1           어린이 교통안전교육          함지초등병설유치원   
790305  2020-11-23    인천지부     3  기관/단체, 기업체 등 교통안전교육  한국가스기술공사 인천지사 교육장   

        교육인원    교육시작시간    교육종료시간  
실적번호                              
777867     5  13:00:00  16:00:00  
777961    25  10:00:00  11:00:00  
777971    25  10:00:00  11:00:00  
778003    20  15:00:00  16:00:00  
778004    10  10:30:00  11:30:00  
...      ...       ...       ...  
784810     8  11:30:00  12:00:00  
784811     8  11:30:00  12:00:00  
788112    17  10:30:00  11:30:00  
789143    20  10:00:00  11:00:00  
790305    15  16:00:00  17:00:00  

[4548 rows x 8 columns]

In [186]:
def dev_people(x):
    if x > 500:
        return '500명 초과'
    elif x <= 500 and x> 30:
        return '500명 이하'
    elif x <=30:
        return '30명 이하'
df3['교육인원그룹'] = df3['교육인원'].apply(lambda x: dev_people(x))    

In [187]:
df_30 =df3['교육인원그룹'] == '30명 이하'
df3[df_30]

교육일자    지부코드  교육구분               교육구분_1               교육장소  \
실적번호                                                                       
777867  2020-01-10    경북지부     2           청소년 교통안전교육           구미 보호관찰소   
777961  2020-01-15    인천지부     4            노인 교통안전교육         인천노인인력개발센터   
777971  2020-01-21    인천지부     4            노인 교통안전교육         인천노인인력개발센터   
778003  2020-01-20    대구지부     2           청소년 교통안전교육     대구행복한미래제단 301호   
778004  2020-01-30    대구지부     3  기관/단체, 기업체 등 교통안전교육        공군 제16전투비행단   
...            ...     ...   ...                  ...                ...   
784810  2020-11-12  광주전남지부     1           어린이 교통안전교육          여수 중앙어린이집   
784811  2020-11-12  광주전남지부     1           어린이 교통안전교육          여수 중앙어린이집   
788112  2020-05-24  울산경남지부     1           어린이 교통안전교육            예다움어린이집   
789143  2020-12-04    대구지부     1           어린이 교통안전교육          함지초등병설유치원   
790305  2020-11-23    인천지부     3  기관/단체, 기업체 등 교통안전교육  한국가스기술공사 인천지사 교육장   

        교육인원    교육시작시간    교육종료시간  교육인원그룹  
실적번호                                      
777867     5  13:00:00  16:00:00  30명 이하  
777961    25  10:00:00  11:00:00  30명 이하  
777971    25  10:00:00  11:00:00  30명 이하  
778003    20  15:00:00  16:00:00  30명 이하  
778004    10  10:30:00  11:30:00  30명 이하  
...      ...       ...       ...     ...  
784810     8  11:30:00  12:00:00  30명 이하  
784811     8  11:30:00  12:00:00  30명 이하  
788112    17  10:30:00  11:30:00  30명 이하  
789143    20  10:00:00  11:00:00  30명 이하  
790305    15  16:00:00  17:00:00  30명 이하  

[4548 rows x 9 columns]

In [37]:
## 답안
def num_count(x):
    if x<=30:
        return True
    else:
        return False

In [40]:
query_expr = '30 < 교육인원 <= 500' ## 쿼리함수말고 다른곳에선 사용 불가
df_500 = df3.query(query_expr)

In [42]:
df_1000 = df3[df3['교육인원'] > 500]

In [14]:
m = df3['교육인원'].apply(lambda x: num_count(x))
df_30 = df3[m]
msg = df_30.value_counts('지부코드').sort_values(ascending=False)

In [45]:
msg = df_30.value_counts('지부코드').sort_values(ascending=False)
print(f'30명 이하 구간에선 {msg.index[0]}가 {msg[0]}건으로 가장 많았습니다.')

30명 이하 구간에선 광주전남지부가 942건으로 가장 많았습니다.


In [54]:
msg.index[0]

'광주전남지부'

In [41]:
msg = df_500.value_counts('지부코드').sort_values(ascending=False)
print(f'500명 이하 구간에선 {msg.index[0]}가 {msg[0]}건으로 가장 많았습니다.')

500명 이하 구간에선 대구지부가 459건으로 가장 많았습니다.


In [43]:
msg = df_1000.value_counts('지부코드').sort_values(ascending=False)
print(f'1000명 이하 구간에선 {msg.index[0]}가 {msg[0]}건으로 가장 많았습니다.')

1000명 이하 구간에선 충북지부가 2건으로 가장 많았습니다.


## 실습 4 
* 아래 데이터프레임에서 주어진 계산을 해보자
    * 자치구명별로 물건금액의 합계를 구한다.(단, 본번 정보가 있는 건물에 한함)
    * 신고한 개업공인중개사 시군구명 column에서 NaN값의 개수를 구한다.
    * 건물면적이 20평 이상인 건물에 대해서만 물건금액의 평균을 구한다
    * 5층 이하인 건물에 대해서만 자치구별로 빈도를 구한다

### 결측치 : NaN, None, nan, NA, N/a, NA!,엑셀의 빈 값, 엑셀의 !VALUE
* 결측치가 있을 경우, 해당 row를 지우는게 일반적
* 단, 결측치가 있는 column이 거의 결측치로 이루어져 있다면, 해당 column을 지우는 것을 권장

#### dropna 함수: NaN 값을 지우는 함수
* 패러미터를 axis = 1로 받을 경우 column단위로 지움
    * 기본값: axis = 0(row단위로 지움)
* 패러미터로 how = 'all'로 받을 경우, 모든 row, column이 NaN일 경우 지움

In [ ]:
import pandas as pd
df5 = pd.read_csv('C:/Users/user/Desktop/230102~/실습 데이터/서울시 부동산 실거래가 정보.csv',encoding='cp949')
df6 = df5.copy()

In [ ]:
df5.head(2)

In [10]:
df5.iloc[:,[7,19,20]] # 결측치 : NaN, None, nan, NA, N/a, NA!,엑셀의 빈 값, 엑셀의 !VALUE

본번  신고구분 신고한 개업공인중개사 시군구명
0         43.0  중개거래           서울 송파구
1          7.0  중개거래            서울 중구
2        295.0  중개거래           서울 중랑구
3        425.0  중개거래           서울 강동구
4         80.0  중개거래           서울 은평구
...        ...   ...              ...
639995    56.0   NaN              NaN
639996  1278.0   NaN              NaN
639997   271.0   NaN              NaN
639998   169.0   NaN              NaN
639999   261.0   NaN              NaN

[640000 rows x 3 columns]

In [63]:
float('nan')

nan

In [188]:
type(float('nan')) == type(0.996) ## 실수와 타입은 같음

True

In [65]:
0.99 == 0.99

True

In [67]:
float('nan') == float('nan') # 이를 이용해 결측치 제거함

False

#### 실습 4-1

In [77]:
for i in df5['자치구명'].unique():
    m = df5['자치구명'] == i
    df6 = df5[m]


array(['송파구', '중구', '중랑구', '강동구', '은평구', '동대문구', '금천구', '성동구', '양천구',
       '서대문구', '도봉구', '강북구', '동작구', '관악구', '영등포구', '구로구', '서초구', '강서구',
       '광진구', '노원구', '강남구', '성북구', '용산구', '종로구', '마포구'], dtype=object)

In [79]:
df5_na_omit = df5.dropna(subset = ['본번']) ## 본번이 결측치인 행을 제거

In [83]:
for i in df5_na_omit['자치구명'].unique():
    m = df5['자치구명'] == i
    print(i, '\t', df5_na_omit[m]['물건금액(만원)'].sum(), '\t만원')

C:\Users\user\AppData\Local\Temp\ipykernel_20376\647544960.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(i, '\t', df5_na_omit[m]['물건금액(만원)'].sum(), '\t만원')


송파구 	 2714820349 	만원
중구 	 405634533 	만원
중랑구 	 795939306 	만원
강동구 	 1453409556 	만원
은평구 	 1335816845 	만원
동대문구 	 883886673 	만원
금천구 	 670158675 	만원
성동구 	 1329873851 	만원
양천구 	 1377262558 	만원
서대문구 	 896689348 	만원
도봉구 	 788640613 	만원
강북구 	 619446115 	만원
동작구 	 1216723230 	만원
관악구 	 873649480 	만원
영등포구 	 1346630498 	만원
구로구 	 1198229714 	만원
서초구 	 2633490080 	만원
강서구 	 1855893441 	만원
광진구 	 843774183 	만원
노원구 	 1353330005 	만원
강남구 	 3159289701 	만원
성북구 	 1175311100 	만원
용산구 	 1280016108 	만원
종로구 	 406760075 	만원
마포구 	 1463054038 	만원


#### 실습 4-2

In [58]:
df5['신고한 개업공인중개사 시군구명'].isnull().sum()

462901

In [189]:
## 답안
ind = 0
for i in df5['신고한 개업공인중개사 시군구명']:
    if i==i:
        pass
    else:
        ind +=1
    ind
ind

462901

In [98]:
df6 = df5['신고한 개업공인중개사 시군구명'].value_counts(dropna= False).to_frame()
df6

신고한 개업공인중개사 시군구명
NaN                               462901
서울 강서구                             16236
서울 강남구                             11468
서울 은평구                             10050
서울 송파구                              9977
...                                  ...
경기 안양만안구 서울 강남구                        1
서울 강남구 제주 제주시                          1
서울 광진구 서울 노원구 서울 중랑구                   1
경기 성남수정구 서울 강남구 서울 송파구                 1
경기 수원장안구 서울 구로구                        1

[736 rows x 1 columns]

#### 실습 4-3

In [190]:
df_20  =df5[df5['건물면적(㎡)'] >=3.3 * 20] ## 실습 4
int(df_20['물건금액(만원)'].mean())

119123

#### 실습 4-4

In [124]:
df_5 = df5['층'] <= 5
df6 = df5[df_5]
df6['자치구명'].unique()

array(['송파구', '중랑구', '은평구', '금천구', '성동구', '양천구', '강동구', '서대문구', '도봉구',
       '동작구', '관악구', '영등포구', '구로구', '서초구', '강서구', '광진구', '노원구', '강북구',
       '성북구', '용산구', '동대문구', '종로구', '마포구', '중구', '강남구'], dtype=object)

In [ ]:
df5[df_5]

In [112]:
## 답안
import pandas as pd
m = df5['층'] <= 5
df_h = df5[m]

In [119]:
df_h['자치구명'].value_counts()

강서구     33643
은평구     28348
송파구     20452
구로구     19641
양천구     19028
강북구     16696
도봉구     15919
강동구     15593
관악구     15312
마포구     14644
중랑구     14260
성북구     13335
강남구     13315
금천구     13252
동작구     13215
노원구     12997
서초구     12655
광진구     10986
서대문구    10786
영등포구    10230
동대문구     8181
용산구      7830
성동구      6319
종로구      5079
중구       3452
Name: 자치구명, dtype: int64

# 230109과제
* 판다스와 넘파이를 이용한 데이터 이용
* 주어진 데이터프레임에서 아래 처리를 한다.
* 뒤에서 3번째 순서의 column을 df_to_arr 파일로 저장(바이너리 파일로)
* 임의의 범위를 슬라이싱한 뒤, 넘파이를 이용해 행렬곱 구하기

In [175]:
df5.iloc[:,-3]

0         연립다세대
1          오피스텔
2         연립다세대
3          오피스텔
4         연립다세대
          ...  
639995      아파트
639996      아파트
639997      아파트
639998    연립다세대
639999    연립다세대
Name: 건물용도, Length: 640000, dtype: object

In [191]:
np.array(df5.iloc[:,-3])
np.savez('./df_to_arr.npy',np.array(df5.iloc[:,-3]))

In [179]:
np1 = df5[['건물면적(㎡)','토지면적(㎡)','층']][50:53]
np2 = df5[['건물면적(㎡)','토지면적(㎡)','층']][100:106]
np1 = np.array(np1)
np2 = np.array(np2)

In [180]:
np2.dot(np1)

array([[2233.8149, 1442.8332,  175.17  ],
       [3176.0636, 2050.0848,  227.8   ],
       [3864.3871, 2495.0628,  301.53  ],
       [ 989.1641,  645.0588,   74.74  ],
       [2077.0681, 1341.7308,  163.98  ],
       [2201.6649, 1421.5932,  172.17  ]])